add Custom marker option interface
veitbjarsch/vue-leaflet-markercluster pull request #20
Opened 2024-01-31 15:21 UTC by qq7

2024-02-08 22:27 UTC, solesonicsteph commented
Really looking forward to this one getting in! Game changer!

2024-02-12 17:48 UTC, solesonicsteph commented
Pulled this code down and tested locally via linking, works like a charm! Any updates on when it might be merged @veitbjarsch ?

2024-02-13 10:21 UTC, veitbjarsch requested changes
Code looks fine and demo works well. Just switch from pnpm to npm please. If this is done I'm going to merge it.

2024-02-13 10:21 UTC, veitbjarsch commented on pnpm-lock.yaml
Can you run the install with npm instead of pnpm. The release pipeline only uses the npm package lock file and it won't build if the package.json is out of sync with the package-lock.json.

2024-02-13 12:56 UTC, veitbjarsch requested changes
Wait one more thing 🙈 
I missed to tell you can you add the change to the Changelog.md please.

2024-02-13 14:29 UTC, veitbjarsch commented
No just under the unreleased part. It will do it automatically once I release a new version.

2024-02-13 14:44 UTC, veitbjarsch commented
Can you put please an:
`### Added` above the line?

2024-02-13 16:48 UTC, veitbjarsch approved these changes
LGTM

2024-02-13 16:50 UTC, merged

2024-02-13 16:59 UTC, veitbjarsch commented
Released new version. Thanks for your effort.